import { assetPath } from "../utils";

export const iconDataMap = {
	// https://www.flaticon.com/premium-icon/difference_4956420?term=different&page=1&position=76&page=1&position=76&related_id=4956420&origin=search
	WindowIcon: [
		assetPath("compare#0.png"),
		assetPath("compare#1.png"),
		assetPath("compare#2.png"),
		assetPath("compare#3.png"),
		assetPath("compare#4.png"),
		assetPath("compare#5.png"),
		assetPath("compare#6.png"),
		assetPath("compare#7.png"),
		assetPath("compare#8.png"),
		assetPath("compare#9.png"),
		assetPath("compare#10.png"),
		assetPath("compare#11.png"),
		assetPath("compare#12.png"),
		assetPath("compare#13.png"),
		assetPath("compare#14.png"),
		assetPath("compare#15.png"),
		assetPath("compare#16.png"),
		assetPath("compare#17.png"),
		assetPath("compare#18.png"),
		assetPath("compare#19.png"),
	],
	Language: [
		assetPath("language#0.png"),
		assetPath("language#1.png"),
		assetPath("language#2.png"),
		assetPath("language#3.png"),
		assetPath("language#4.png"),
		assetPath("language#5.png"),
		assetPath("language#6.png"),
		assetPath("language#7.png"),
		assetPath("language#8.png"),
		assetPath("language#9.png"),
		assetPath("language#10.png"),
		assetPath("language#11.png"),
		assetPath("language#12.png"),
		assetPath("language#13.png"),
		assetPath("language#14.png"),
		assetPath("language#15.png"),
		assetPath("language#16.png"),
		assetPath("language#17.png"),
		assetPath("language#18.png"),
		assetPath("language#19.png"),
	],
};

export type IconDataMapType = Record<keyof typeof iconDataMap, number>;
